const fs = require('fs');
const { wrapHostedFunction } = require('../hosting.utils');

const generateHostedJs = ({
  hostedHandlers,
}) => {
  const exportLines = [];
  const hostingUtilsRequire = '@foxtware/mineral/hosting.utils';

  for (const hostedHandler of hostedHandlers) {
    const { entryPoint, wrappers = [], requirePath } = hostedHandler;
    const wrappersArg = wrappers.length ? `, ${ JSON.stringify(wrappers) }` : '';

    exportLines.push(
      `  ${ entryPoint }: wrapHostedFunction(() => require('${ requirePath }'), '${ entryPoint }'${ wrappersArg }),`,
    );
  }

  return `// Generated by mineral — do not edit
const { wrapHostedFunction } = require('${ hostingUtilsRequire }');

module.exports = {
${ exportLines.join('\n') }
};
`;
};

const writeHostedJs = ({
  workspace,
  hostedHandlers,
}) => {
  const hostedPath = `${ workspace.replace(/\/$/, '') }/hosted.js`;
  const content = generateHostedJs({
    hostedHandlers,
  });

  fs.writeFileSync(hostedPath, content);
  return hostedPath;
};

module.exports = {
  generateHostedJs,
  writeHostedJs,
};
