const fs = require('fs');
const { wrapHostedFunction, parseWrapperRef } = require('../hosting.utils');

const formatWrapperRefForHostedJs = (wrapperRef) => {
  const { modulePath, exportName } = parseWrapperRef(wrapperRef);
  return `require('${ modulePath }').${ exportName }`;
};

const formatWrappersArg = (wrappers = []) => {
  if (!wrappers.length) {
    return '';
  }

  const wrapperLines = wrappers.map((wrapperRef) => `    ${ formatWrapperRefForHostedJs(wrapperRef) },`);
  return `, [\n${ wrapperLines.join('\n') }\n  ]`;
};

const generateHostedJs = ({
  hostedHandlers,
}) => {
  const exportLines = [];

  for (const hostedHandler of hostedHandlers) {
    const { entryPoint, wrappers = [], requirePath } = hostedHandler;
    const wrappersArg = formatWrappersArg(wrappers);

    exportLines.push(
      `  ${ entryPoint }: wrapHostedFunction(() => require('${ requirePath }'), '${ entryPoint }'${ wrappersArg }),`,
    );
  }

  return `// Generated by mineral — do not edit
const { wrapHostedFunction } = require('@foxtware/mineral/hosting.utils');

module.exports = {
${ exportLines.join('\n') }
};
`;
};

const writeHostedJs = ({
  workspace,
  hostedHandlers,
}) => {
  const hostedPath = `${ workspace.replace(/\/$/, '') }/hosted.js`;
  const content = generateHostedJs({
    hostedHandlers,
  });

  fs.writeFileSync(hostedPath, content);
  return hostedPath;
};

module.exports = {
  generateHostedJs,
  writeHostedJs,
};
