const fs = require('fs');
const path = require('path');
const { wrapHostedFunction } = require('../hosting.utils');

const hostingUtilsRequirePath = (workspace) => (
  fs.existsSync(path.join(workspace, 'hosting.utils.js'))
    ? './hosting.utils'
    : '@foxtware/mineral/hosting.utils'
);

const generateHostedJs = ({
  workspace,
  hostedEntries,
  handlerByRouteName,
}) => {
  const exportLines = [];
  const hostingUtilsRequire = hostingUtilsRequirePath(workspace);

  for (const hostedEntry of hostedEntries) {
    const { entryPoint, wrappers = [] } = hostedEntry;
    const handler = handlerByRouteName.get(entryPoint);
    if (!handler) {
      throw new Error(`No handler found for entry_point: ${ entryPoint }`);
    }

    const relativePath = `./${ handler.filePath.slice(workspace.length + 1) }`;
    const wrappersArg = wrappers.length ? `, ${ JSON.stringify(wrappers) }` : '';

    exportLines.push(
      `  ${ entryPoint }: wrapHostedFunction(() => require('${ relativePath }'), '${ entryPoint }'${ wrappersArg }),`,
    );
  }

  return `// Generated by mineral — do not edit
const { wrapHostedFunction } = require('${ hostingUtilsRequire }');

module.exports = {
${ exportLines.join('\n') }
};
`;
};

const writeHostedJs = ({
  workspace,
  hostedEntries,
  handlerByRouteName,
}) => {
  const hostedPath = path.join(workspace, 'hosted.js');
  const content = generateHostedJs({
    workspace,
    hostedEntries,
    handlerByRouteName,
  });

  fs.writeFileSync(hostedPath, content);
  return hostedPath;
};

module.exports = {
  generateHostedJs,
  writeHostedJs,
};
