const fs = require('fs');
const { wrapHostedFunction } = require('./hosting.utils');

const requirePathForHostedJs = (modulePath) => {
  if (modulePath === './hosting/wrappers.js') {
    return './wrappers.js';
  }

  if (modulePath.startsWith('./api/')) {
    return `../${ modulePath.slice(2) }`;
  }

  return modulePath;
};

const formatResolvedWrapperForHostedJs = ({ modulePath, wrapperName }) => (
  `require('${ requirePathForHostedJs(modulePath) }').${ wrapperName }`
);

const formatWrapperList = (resolvedWrappers = []) => {
  if (!resolvedWrappers.length) {
    return '';
  }

  const wrapperLines = resolvedWrappers.map((resolvedWrapper) => (
    `      ${ formatResolvedWrapperForHostedJs(resolvedWrapper) },`
  ));

  return `\n${ wrapperLines.join('\n') }\n    `;
};

const formatWrappersArg = ({
  resolvedBeforeWrappers = [],
  resolvedAfterWrappers = [],
} = {}) => {
  if (!resolvedBeforeWrappers.length && !resolvedAfterWrappers.length) {
    return '';
  }

  const beforeWrappersBlock = formatWrapperList(resolvedBeforeWrappers);
  const afterWrappersBlock = formatWrapperList(resolvedAfterWrappers);

  return `, {
    beforeWrappers: [${ beforeWrappersBlock }],
    afterWrappers: [${ afterWrappersBlock }],
  }`;
};

const generateHostedJs = ({
  hostedHandlers,
}) => {
  const exportLines = [];

  for (const hostedHandler of hostedHandlers) {
    const {
      hostedName,
      handlerName,
      resolvedBeforeWrappers = [],
      resolvedAfterWrappers = [],
      requirePath,
    } = hostedHandler;
    const wrappersArg = formatWrappersArg({
      resolvedBeforeWrappers,
      resolvedAfterWrappers,
    });

    exportLines.push(
      `  ${ hostedName }: wrapHostedFunction(() => require('${ requirePathForHostedJs(requirePath) }'), '${ handlerName }'${ wrappersArg }),`,
    );
  }

  return `// Generated by mineral — do not edit
const { wrapHostedFunction } = require('@foxtware/mineral/hosting/hosting.utils');

module.exports = {
${ exportLines.join('\n') }
};
`;
};

const writeHostedJs = ({
  workspace,
  hostedHandlers,
}) => {
  const { getHostingDir } = require('./hosting.utils');
  const hostedPath = `${ getHostingDir(workspace) }/hosted.js`;
  const content = generateHostedJs({
    hostedHandlers,
  });

  fs.mkdirSync(getHostingDir(workspace), { recursive: true });
  fs.writeFileSync(hostedPath, content);
  return hostedPath;
};

module.exports = {
  generateHostedJs,
  writeHostedJs,
};
