const fs = require('fs');
const { wrapHostedFunction } = require('./hosting.utils');

const formatResolvedWrapperForHostedJs = ({ modulePath, wrapperName }) => (
  `require('${ modulePath }').${ wrapperName }`
);

const formatWrappersArg = (resolvedWrappers = []) => {
  if (!resolvedWrappers.length) {
    return '';
  }

  const wrapperLines = resolvedWrappers.map((resolvedWrapper) => (
    `    ${ formatResolvedWrapperForHostedJs(resolvedWrapper) },`
  ));
  return `, [\n${ wrapperLines.join('\n') }\n  ]`;
};

const generateHostedJs = ({
  hostedHandlers,
}) => {
  const exportLines = [];

  for (const hostedHandler of hostedHandlers) {
    const { hostedName, handlerName, resolvedWrappers = [], requirePath } = hostedHandler;
    const wrappersArg = formatWrappersArg(resolvedWrappers);

    exportLines.push(
      `  ${ hostedName }: wrapHostedFunction(() => require('${ requirePath }'), '${ handlerName }'${ wrappersArg }),`,
    );
  }

  return `// Generated by mineral — do not edit
const { wrapHostedFunction } = require('@foxtware/mineral/hosting/hosting.utils');

module.exports = {
${ exportLines.join('\n') }
};
`;
};

const writeHostedJs = ({
  workspace,
  hostedHandlers,
}) => {
  const { getHostingDir } = require('./hosting.utils');
  const hostedPath = `${ getHostingDir(workspace) }/hosted.js`;
  const content = generateHostedJs({
    hostedHandlers,
  });

  fs.mkdirSync(getHostingDir(workspace), { recursive: true });
  fs.writeFileSync(hostedPath, content);
  return hostedPath;
};

module.exports = {
  generateHostedJs,
  writeHostedJs,
};
